### PR TITLE
fix: accessibility issue of no lang attribute

### LINKED ISSUE #147: a11y quick wins : lang attribute in index.html
Can we add the lang attribute to index.html mentioning the value to en, it is the first accessibility error I have encountered? Would love to submit a PR if it is OK...

### PR DESCRIPTION
**Pull request by rajasegar**
Fixes #147 
Using Chrome Dev Tools Accessibility audit
## Before:

Screenshot 2020-04-01 at 11 05 59 AM

## After:

Screenshot 2020-04-01 at 11 06 30 AM

### CODE REVIEW

**Comment by chancancode** [comment]
Hi @rajasegar, thank you! Sorry I didn't pay enough attention when replying from my phone. We should totally do these changes, but these files are generated from the executable markdown in https://github.com/ember-learn/super-rentals-tutorial/, so we should make the changes there along with the accompanying explanatory text. For this change, I think it somewhere towards the end of the first chapter ([source](https://raw.githubusercontent.com/ember-learn/super-rentals-tutorial/master/src/markdown/tutorial/part-1/01-orientation.md) | [rendered](https://guides.emberjs.com/release/tutorial/part-1/orientation/)) would be a good place for this. What do you think?

**Comment by rajasegar** [comment]
Sure @chancancode sounds good. I will create a PR there also.

**Comment by MelSumner** [comment]
@rajasegar were you able to create the PR in the correct place? I'm going to go ahead and close this issue on this repo. 👍

**Comment by rajasegar** [comment]
@MelSumner Yes, I think I got it where, will create a PR there asap

**Pull request closed without merging**
