### PR TITLE
Mention lodash issue needing npm2

### PR DESCRIPTION
**Pull request by toddjordan**
Addresses issue #16

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm.  I'm using ember-cli-mirage at work just fine with npm3.  Maybe we need to upgrade?

**Comment by toddjordan** [comment]
@rwjblue could be... I do have another open PR for a 2.5 upgrade.  I can try there.  What version of mirage are you using?

**Comment by toddjordan** [comment]
OK, updated everything to the lastest release:
ember 2.5.1
ember-data 2.5.2
ember-cli-mirage 0.2.0-beta.8
ember-lodash 0.0.7

and now it works.  Not sure which upgrade was the golden nugget though.  

Closing this PR and commenting in the issue.

**Comment by toddjordan** [comment]
Also will add the new versions to the upgrade pull request.

**Pull request closed without merging**
