### PR TITLE
Switch to  es5 getters

### PR DESCRIPTION
**Pull request by kennethlarsen**
Issue reference: https://github.com/emberjs/guides/issues/2303

### CODE REVIEW

**Comment by yawboakye** [comment]
@kennethlarsen :+1: Should be good to go after the conflict is resolved. Then we can merge the PR on the Guides as well. cc/ @locks @acorncom

**Comment by acorncom** [comment]
@kennethlarsen still interested in getting this merged in, would you have time to resolve the conflicts here?

**Comment by kennethlarsen** [comment]
@acorncom Sure! There were some concerns or doubts in the learning team whether they actually wanted this or not. But if that's resolved I'll happily resolve the conflicts.

**Comment by kennethlarsen** [comment]
@acorncom Looks like yarn is breaking CI. Not sure what to do here

**Review by sivakumar-kailasam — CHANGES_REQUESTED** [review]
Can we update this to latest stable instead of an old beta?

**Pull request merged**
